-- Insere a Política de Privacidade e os Termos de Uso na tabela platform_content.
-- O conteúdo é em Markdown e renderizado no frontend via marked.
-- Usar upsert para não quebrar caso já exista um rascunho.

INSERT INTO platform_content (key, content, updated_at)
VALUES (
  'privacidade',
  E'## 1. Quem somos\n\nA **Tipo7.com** é uma plataforma brasileira de venda e gestão de ingressos para eventos, operada pela empresa responsável pelo domínio tipo7.com. Neste documento, "nós", "nosso" ou "Tipo7" referem-se à plataforma.\n\n## 2. Quais dados coletamos\n\nColetamos apenas os dados necessários para prestar o serviço:\n\n- **Dados de cadastro:** nome completo, e-mail, telefone, CPF e data de nascimento.\n- **Dados de pagamento:** processados integralmente pelo Mercado Pago. Não armazenamos dados de cartão.\n- **Dados de uso:** endereço IP, tipo de dispositivo e páginas visitadas, para segurança e melhoria do serviço.\n- **Login social:** quando você usa Google ou Facebook para entrar, recebemos apenas nome, e-mail e foto de perfil autorizados por você.\n\n## 3. Para que usamos seus dados\n\n- Criar e gerenciar sua conta\n- Processar compras e enviar seus ingressos por e-mail\n- Comunicar informações sobre pedidos e eventos\n- Prevenir fraudes e garantir a segurança da plataforma\n- Cumprir obrigações legais\n\n## 4. Com quem compartilhamos\n\nNão vendemos seus dados. Compartilhamos apenas com:\n\n- **Mercado Pago:** para processar pagamentos\n- **Supabase:** infraestrutura de banco de dados (servidores no Brasil/EUA)\n- **Resend:** para envio de e-mails transacionais\n- **Organizadores de eventos:** nome e e-mail do comprador para fins de controle de acesso\n\n## 5. Seus direitos (LGPD)\n\nVocê pode, a qualquer momento:\n\n- Acessar, corrigir ou excluir seus dados\n- Revogar o consentimento para uso dos seus dados\n- Solicitar a portabilidade dos seus dados\n\nPara exercer esses direitos, entre em contato: **contato@tipo7.com**\n\n## 6. Cookies\n\nUsamos cookies essenciais para manter sua sessão ativa. Não usamos cookies de rastreamento de terceiros para publicidade.\n\n## 7. Segurança\n\nAdotamos criptografia em trânsito (HTTPS), tokens de acesso de curta duração e controles de acesso baseados em funções para proteger seus dados.\n\n## 8. Menores de idade\n\nNosso serviço não é destinado a menores de 18 anos. Não coletamos dados de menores intencionalmente.\n\n## 9. Alterações nesta política\n\nPoderemos atualizar esta política periodicamente. Alterações relevantes serão comunicadas por e-mail ou aviso na plataforma.\n\n## 10. Contato\n\nDúvidas sobre privacidade: **contato@tipo7.com**',
  NOW()
)
ON CONFLICT (key) DO UPDATE
  SET content    = EXCLUDED.content,
      updated_at = EXCLUDED.updated_at;

INSERT INTO platform_content (key, content, updated_at)
VALUES (
  'termos',
  E'## 1. Aceitação dos termos\n\nAo criar uma conta ou comprar ingressos na **Tipo7.com**, você concorda com estes Termos de Uso. Se não concordar, não utilize a plataforma.\n\n## 2. O que é a Tipo7.com\n\nA Tipo7.com é uma plataforma intermediária que conecta organizadores de eventos a compradores de ingressos. Não somos organizadores dos eventos listados e não nos responsabilizamos por cancelamentos, alterações ou qualidade dos eventos.\n\n## 3. Cadastro\n\n- Você deve ter 18 anos ou mais para criar uma conta\n- As informações fornecidas devem ser verdadeiras e atualizadas\n- Você é responsável pela segurança da sua senha\n- Uma conta por pessoa física — contas duplicadas podem ser removidas\n\n## 4. Compra de ingressos\n\n- Os preços exibidos já incluem todas as taxas aplicáveis\n- O pagamento é processado pelo Mercado Pago\n- O ingresso é enviado por e-mail após a confirmação do pagamento\n- Cada ingresso possui um QR Code único e intransferível para validação na entrada\n\n## 5. Política de reembolso\n\n- Cancelamentos solicitados em até **48 horas** após a compra e com mais de 7 dias antes do evento podem ser reembolsados\n- Reembolsos são processados no mesmo método de pagamento em até 10 dias úteis\n- Eventos cancelados pelos organizadores geram reembolso integral automático\n- Não realizamos reembolso por arrependimento após o prazo acima\n\n## 6. Responsabilidades do organizador\n\nOrganizadores que utilizam a Tipo7.com para vender ingressos são responsáveis por:\n\n- A realização do evento conforme anunciado\n- A veracidade das informações publicadas\n- O atendimento ao público no local\n- O cumprimento das leis aplicáveis ao evento\n\n## 7. Proibições\n\nÉ proibido:\n\n- Revender ingressos acima do valor de face (cambismo)\n- Usar bots ou scripts para comprar ingressos em massa\n- Tentar fraudar o sistema de validação de QR Codes\n- Criar contas falsas ou usar dados de terceiros sem autorização\n\n## 8. Propriedade intelectual\n\nTodo o conteúdo da plataforma (marca, design, código) é de propriedade da Tipo7.com. É proibida a reprodução sem autorização expressa.\n\n## 9. Limitação de responsabilidade\n\nA Tipo7.com não se responsabiliza por danos decorrentes de:\n\n- Cancelamento ou alteração de eventos por terceiros\n- Falhas de conexão à internet do usuário\n- Uso indevido de credenciais de acesso\n\n## 10. Alterações nos termos\n\nPodemos atualizar estes termos a qualquer momento. Alterações entram em vigor 15 dias após a publicação. O uso continuado da plataforma após esse prazo implica aceitação.\n\n## 11. Foro\n\nFica eleito o foro da comarca de São Paulo/SP para dirimir quaisquer controvérsias decorrentes destes termos.\n\n## 12. Contato\n\nDúvidas: **contato@tipo7.com**',
  NOW()
)
ON CONFLICT (key) DO UPDATE
  SET content    = EXCLUDED.content,
      updated_at = EXCLUDED.updated_at;
